name: api-client-gen
author: Usman Ayupov <au073@mail.ru>
description: Generate API Clients by Swagger
inputs:
  inputFile:
    description: Path to swagger.json file
    required: true
    default: ""
  outputDirectory:
    description: Path to output files directory
    required: true
    default: ""
  language:
    description: Programming language for which clients will be generated
    required: true
    default: ""

outputs:
  result:
    description: The state of the action, if the API Clients generated successfully

runs:
  using: composite
  steps:
    - shell: bash
      run: |
        docker build -t api-client-gen .
        docker run -u 1001 --rm --workdir /github/workspace -v "$GITHUB_WORKSPACE":"/github/workspace" api-client-gen \
          -inputFile /github/workspace/${{ inputs.inputFile }} \
          -outputDirectory /github/workspace/${{ inputs.outputDirectory }} \
          -language ${{ inputs.language }}

branding:
  icon: code
  color: blue
